spring.application.name=TruthNet-Transformer-Backend

# Aiven MySQL Database
spring.datasource.url=jdbc:mysql://truthnetdata-mohdfazalahamd-1ace.g.aivencloud.com:26818/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}